# -*- coding: utf-8 -*-
"""Q1_Narra_FA1_Belmes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VGmMYVfsKDfLqvcDE1hsOWpzGQijS1S-

# Grade 8 (nahrrah)


---

### FA in Libraries and Predefined Functions
"""

import math # Imports the math library.

# Ask for the X and Y positions for each of the points, and casts them to floats as input() returns a string.
# Float is used for increased precision.
x1 = float(input("Enter x1: "))
y1 = float(input("Enter y1: "))

x2 = float(input("Enter x2: "))
y2 = float(input("Enter y2: "))

# Use the Euclidean formula for distance. We utilize the math library here.
output = math.sqrt(math.pow(x2 - x1, 2) + math.pow(y2 - y1, 2))

# We want to show the output as it is only a variable, so we must print it.
# Round it to two decimal places for a presentable output.
print("The distance between the two points is:", round(output,2))

# Using a library is more practical than writing all the calculations from scratch,
# as it helps optimize your code and lets it conform to the DRY (Don't Repeat Yourself) principle in programming.
# As an example, my code does not need to include any written implementation of exponentiation or square roots,
# because the math library already has them written in its code.
# If I didn't use the math library, I'd need to manually implement math.pow() and math.sqrt(), which would not
# only be difficult, but also require more knowledge and time.